import AppKit
import Carbon.HIToolbox
import Combine

// MARK: - Tipos marcadores de privacidad del portapapeles (convención nspasteboard.com)

enum PasteboardPrivacyTypes {
    static let concealed     = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient     = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

// MARK: - Combinación de teclas del atajo global (en espacio Carbon)

struct KeyCombo: Equatable {
    var keyCode: UInt32
    var carbonModifiers: UInt32

    /// Atajo del panel por defecto: ⌘⇧E (Cmd+Shift+E). Evita defaults del sistema.
    static let defaultCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_E),
                                       carbonModifiers: UInt32(cmdKey | shiftKey))
    /// Atajo de voz por defecto: ⌘⇧I (Cmd+Shift+I).
    static let defaultVoiceCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_I),
                                            carbonModifiers: UInt32(cmdKey | shiftKey))
    /// Atajo de captura por defecto: ⌘⇧U (Cmd+Shift+U). Letra (no número) para no chocar con apps que
    /// secuestran ⌘⇧2 (p. ej. Loom) y para acompañar a ⌘⇧E / ⌘⇧I.
    static let defaultCaptureCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_U),
                                              carbonModifiers: UInt32(cmdKey | shiftKey))
    /// ⌘⇧4 (el de captura nativo de macOS) — para "reemplazar ⌘⇧4".
    static let cmdShift4Combo = KeyCombo(keyCode: UInt32(kVK_ANSI_4),
                                         carbonModifiers: UInt32(cmdKey | shiftKey))
    /// Antiguo default de captura (⌘⇧2), usado solo para migrar a ⌘⇧U a quien lo tenga persistido.
    static let legacyCaptureCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_2),
                                             carbonModifiers: UInt32(cmdKey | shiftKey))

    var isValid: Bool { carbonModifiers != 0 }

    var displayString: String {
        var s = ""
        if carbonModifiers & UInt32(controlKey) != 0 { s += "⌃" }
        if carbonModifiers & UInt32(optionKey)  != 0 { s += "⌥" }
        if carbonModifiers & UInt32(shiftKey)   != 0 { s += "⇧" }
        if carbonModifiers & UInt32(cmdKey)     != 0 { s += "⌘" }
        s += KeyCombo.keyName(for: keyCode)
        return s
    }

    static func keyName(for keyCode: UInt32) -> String {
        let map: [UInt32: String] = [
            UInt32(kVK_ANSI_A): "A", UInt32(kVK_ANSI_B): "B", UInt32(kVK_ANSI_C): "C",
            UInt32(kVK_ANSI_D): "D", UInt32(kVK_ANSI_E): "E", UInt32(kVK_ANSI_F): "F",
            UInt32(kVK_ANSI_G): "G", UInt32(kVK_ANSI_H): "H", UInt32(kVK_ANSI_I): "I",
            UInt32(kVK_ANSI_J): "J", UInt32(kVK_ANSI_K): "K", UInt32(kVK_ANSI_L): "L",
            UInt32(kVK_ANSI_M): "M", UInt32(kVK_ANSI_N): "N", UInt32(kVK_ANSI_O): "O",
            UInt32(kVK_ANSI_P): "P", UInt32(kVK_ANSI_Q): "Q", UInt32(kVK_ANSI_R): "R",
            UInt32(kVK_ANSI_S): "S", UInt32(kVK_ANSI_T): "T", UInt32(kVK_ANSI_U): "U",
            UInt32(kVK_ANSI_V): "V", UInt32(kVK_ANSI_W): "W", UInt32(kVK_ANSI_X): "X",
            UInt32(kVK_ANSI_Y): "Y", UInt32(kVK_ANSI_Z): "Z",
            UInt32(kVK_ANSI_0): "0", UInt32(kVK_ANSI_1): "1", UInt32(kVK_ANSI_2): "2",
            UInt32(kVK_ANSI_3): "3", UInt32(kVK_ANSI_4): "4", UInt32(kVK_ANSI_5): "5",
            UInt32(kVK_ANSI_6): "6", UInt32(kVK_ANSI_7): "7", UInt32(kVK_ANSI_8): "8",
            UInt32(kVK_ANSI_9): "9",
            UInt32(kVK_Space): "Espacio", UInt32(kVK_Return): "↩", UInt32(kVK_Tab): "⇥",
            UInt32(kVK_Escape): "⎋", UInt32(kVK_Delete): "⌫",
            UInt32(kVK_ANSI_Period): ".", UInt32(kVK_ANSI_Comma): ",",
            UInt32(kVK_ANSI_Slash): "/", UInt32(kVK_ANSI_Semicolon): ";"
        ]
        return map[keyCode] ?? String(format: "Tecla %02X", keyCode)
    }

    /// Combinaciones sugeridas para elegir sin grabar (se muestran en Preferencias).
    static let suggestions: [KeyCombo] = [
        KeyCombo(keyCode: UInt32(kVK_ANSI_E), carbonModifiers: UInt32(cmdKey | shiftKey)),   // ⌘⇧E
        KeyCombo(keyCode: UInt32(kVK_ANSI_I), carbonModifiers: UInt32(cmdKey | shiftKey)),   // ⌘⇧I
        KeyCombo(keyCode: UInt32(kVK_ANSI_U), carbonModifiers: UInt32(cmdKey | shiftKey)),   // ⌘⇧U (captura)
        KeyCombo(keyCode: UInt32(kVK_ANSI_Y), carbonModifiers: UInt32(cmdKey | shiftKey)),   // ⌘⇧Y
        KeyCombo(keyCode: UInt32(kVK_ANSI_M), carbonModifiers: UInt32(cmdKey | shiftKey)),   // ⌘⇧M
        KeyCombo(keyCode: UInt32(kVK_Space),  carbonModifiers: UInt32(optionKey)),           // ⌥Espacio
        KeyCombo(keyCode: UInt32(kVK_Space),  carbonModifiers: UInt32(optionKey | shiftKey)) // ⌥⇧Espacio
    ]
}

// MARK: - Método de envío de email

/// Método con el que la app manda los correos. El default reproduce el comportamiento previo (DWD).
enum MailMethod: String, CaseIterable, Identifiable {
    // Google Workspace: OAuth de escritorio POR USUARIO (scope gmail.send). Cada quien autoriza su
    // propia cuenta y solo envía como sí mismo → sin llave que impersone a otros del dominio.
    case oauth
    case smtp    // SMTP manual: host/puerto/usuario/contraseña propios.
    case systemMail // Mail del sistema: abre el compositor nativo (NSSharingService) con la imagen.

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .oauth:      return "Google Workspace"
        case .smtp:       return "SMTP"
        case .systemMail: return "Mail del sistema"
        }
    }
}

func cocoaToCarbonModifiers(_ flags: NSEvent.ModifierFlags) -> UInt32 {
    var carbon: UInt32 = 0
    if flags.contains(.command) { carbon |= UInt32(cmdKey) }
    if flags.contains(.shift)   { carbon |= UInt32(shiftKey) }
    if flags.contains(.option)  { carbon |= UInt32(optionKey) }
    if flags.contains(.control) { carbon |= UInt32(controlKey) }
    return carbon
}

// MARK: - Almacén de ajustes (UserDefaults), única fuente de verdad

final class Settings: ObservableObject {
    static let shared = Settings()
    private let d = UserDefaults.standard

    private enum K {
        static let maxItems   = "maxItems"
        static let keyCode    = "hotKeyCode"
        static let mods       = "hotKeyModifiers"
        static let autoPaste  = "autoPaste"
        static let concealed  = "privacy.ignoreConcealed"
        static let transient  = "privacy.ignoreTransient"
        static let autoGen    = "privacy.ignoreAutoGenerated"
        static let excluded   = "privacy.excludedBundleIDs"
        static let captureSrc = "captureSource"
        static let detectRem  = "detectRemoteSource"
        static let transModel = "transcriptionModel"
        static let geminiModel = "geminiModel"
        static let transLang  = "transcriptionLanguage"
        static let aiProv     = "aiProvider"
        static let transFallback = "transcriptionFallback"
        static let alwaysOnTop = "alwaysOnTop"
        static let overrideCmd4 = "overrideSystemCapture"
        static let pendingCmd4Verify = "pendingCmd4Verify"
        static let keyCode2   = "voiceHotKeyCode"
        static let mods2      = "voiceHotKeyModifiers"
        static let keyCode3   = "captureHotKeyCode"
        static let mods3      = "captureHotKeyModifiers"
        static let uiLang     = "uiLanguage"
        static let uploadEndpoint = "uploadEndpoint"
        static let mailApiToken = "mailApiToken"
        static let mailFrom     = "mailFrom"
        // Método de envío seleccionable y sus campos por método.
        static let mailMethod   = "mailMethod"
        static let smtpHost     = "smtpHost"
        static let smtpPort     = "smtpPort"
        static let smtpUser     = "smtpUser"
        static let smtpFrom     = "smtpFrom"
        static let googleClientId     = "googleClientId"
        static let googleClientSecret = "googleClientSecret"
        static let googleAccountEmail = "googleAccountEmail"  // email conectado (estado UI), no secreto
    }

    @Published var maxItems: Int          { didSet { d.set(maxItems, forKey: K.maxItems) } }
    @Published var combo: KeyCombo        { didSet {
        d.set(Int(combo.keyCode), forKey: K.keyCode)
        d.set(Int(combo.carbonModifiers), forKey: K.mods)
    } }
    @Published var autoPaste: Bool        { didSet { d.set(autoPaste, forKey: K.autoPaste) } }
    @Published var ignoreConcealed: Bool  { didSet { d.set(ignoreConcealed, forKey: K.concealed) } }
    @Published var ignoreTransient: Bool  { didSet { d.set(ignoreTransient, forKey: K.transient) } }
    @Published var ignoreAutoGenerated: Bool { didSet { d.set(ignoreAutoGenerated, forKey: K.autoGen) } }
    @Published var excludedBundleIDs: [String] { didSet { d.set(excludedBundleIDs, forKey: K.excluded) } }
    @Published var captureSource: Bool    { didSet { d.set(captureSource, forKey: K.captureSrc) } }
    @Published var detectRemoteSource: Bool { didSet { d.set(detectRemoteSource, forKey: K.detectRem) } }
    @Published var transcriptionModel: String { didSet { d.set(transcriptionModel, forKey: K.transModel) } }
    /// Modelo de Google Gemini para transcripción (configurable; antes fijo en "gemini-flash-latest").
    @Published var geminiModel: String { didSet { d.set(geminiModel, forKey: K.geminiModel) } }
    @Published var transcriptionLanguage: String { didSet { d.set(transcriptionLanguage, forKey: K.transLang) } }
    /// Proveedor de IA para transcripción: "openai" o "gemini".
    @Published var aiProvider: String { didSet { d.set(aiProvider, forKey: K.aiProv) } }
    /// Si el proveedor elegido (Gemini) falla, reintenta con OpenAI cuando haya clave.
    @Published var transcriptionFallback: Bool { didSet { d.set(transcriptionFallback, forKey: K.transFallback) } }
    /// Fijar el panel de historial: no se auto-cierra al hacer clic fuera ni al capturar.
    @Published var alwaysOnTop: Bool { didSet { d.set(alwaysOnTop, forKey: K.alwaysOnTop) } }
    /// Reemplazar ⌘⇧4 de macOS: Klip desactiva la captura del sistema y la reclama.
    @Published var overrideSystemCapture: Bool { didSet { d.set(overrideSystemCapture, forKey: K.overrideCmd4) } }
    /// Esperando que el usuario cierre sesión para que ⌘⇧4 quede libre; se verifica al re-arrancar.
    @Published var pendingCmd4Verify: Bool { didSet { d.set(pendingCmd4Verify, forKey: K.pendingCmd4Verify) } }
    @Published var voiceCombo: KeyCombo   { didSet {
        d.set(Int(voiceCombo.keyCode), forKey: K.keyCode2)
        d.set(Int(voiceCombo.carbonModifiers), forKey: K.mods2)
    } }
    @Published var captureCombo: KeyCombo { didSet {
        d.set(Int(captureCombo.keyCode), forKey: K.keyCode3)
        d.set(Int(captureCombo.carbonModifiers), forKey: K.mods3)
    } }
    @Published var uiLanguage: String     { didSet { d.set(uiLanguage, forKey: K.uiLang) } }
    /// Servidor de subida de capturas (estilo Lightshot). POST multipart a `<endpoint>/upload`,
    /// devuelve `{"url": "…"}`. Los links se auto-purgan a los 3 días (etapa de pruebas).
    @Published var uploadEndpoint: String { didSet { d.set(uploadEndpoint, forKey: K.uploadEndpoint) } }
    /// Shared secret para los endpoints de email del server (POST /send). Va en el header `X-Klip-Token`.
    @Published var mailApiToken: String { didSet { d.set(mailApiToken, forKey: K.mailApiToken) } }
    /// Remitente por defecto (usuario actual a impersonar vía DWD en el server). Editable en el compositor.
    @Published var mailFrom: String { didSet { d.set(mailFrom, forKey: K.mailFrom) } }

    /// Método de envío seleccionado en Preferencias → Email. Default "dwd" (comportamiento previo).
    @Published var mailMethod: MailMethod { didSet { d.set(mailMethod.rawValue, forKey: K.mailMethod) } }

    // MARK: Campos del método SMTP (la contraseña va CIFRADA en SecretStore, no aquí).
    @Published var smtpHost: String { didSet { d.set(smtpHost, forKey: K.smtpHost) } }
    @Published var smtpPort: Int    { didSet { d.set(smtpPort, forKey: K.smtpPort) } }
    @Published var smtpUser: String { didSet { d.set(smtpUser, forKey: K.smtpUser) } }
    @Published var smtpFrom: String { didSet { d.set(smtpFrom, forKey: K.smtpFrom) } }

    // MARK: Campos del método OAuth (el refresh token va CIFRADO en SecretStore).
    /// Client ID/secret del OAuth client de escritorio (los configura el dueño; vacíos por default).
    @Published var googleClientId: String     { didSet { d.set(googleClientId, forKey: K.googleClientId) } }
    @Published var googleClientSecret: String { didSet { d.set(googleClientSecret, forKey: K.googleClientSecret) } }
    /// Email de la cuenta conectada (solo estado para la UI; no es secreto).
    @Published var googleAccountEmail: String { didSet { d.set(googleAccountEmail, forKey: K.googleAccountEmail) } }

    /// Toggle maestro de los tres filtros de privacidad. El setter los mueve juntos, así que el
    /// getter usa AND (maestro = "todos activos") para que get/set sean consistentes en el binding
    /// del Toggle y no haya estados intermedios ambiguos.
    var ignoreSensitive: Bool {
        get { ignoreConcealed && ignoreTransient && ignoreAutoGenerated }
        set { ignoreConcealed = newValue; ignoreTransient = newValue; ignoreAutoGenerated = newValue }
    }

    private init() {
        Settings.migrateLegacyDefaultsIfNeeded()
        d.register(defaults: [
            K.maxItems: 200,
            K.keyCode: Int(kVK_ANSI_E),
            K.mods: Int(cmdKey | shiftKey),
            K.autoPaste: true,
            K.concealed: true,
            K.transient: true,
            K.autoGen: true,
            K.captureSrc: true,
            K.detectRem: true,
            K.transModel: "gpt-4o-mini-transcribe",
            K.geminiModel: "gemini-flash-latest",
            K.transLang: "es",
            K.aiProv: "openai",
            K.transFallback: true,
            K.alwaysOnTop: false,
            K.overrideCmd4: false,
            K.pendingCmd4Verify: false,
            K.keyCode2: Int(kVK_ANSI_I),
            K.mods2: Int(cmdKey | shiftKey),
            K.keyCode3: Int(kVK_ANSI_U),
            K.mods3: Int(cmdKey | shiftKey),
            K.uiLang: "en",   // English es el idioma base/por defecto (colaboración open-source); conmutable
            K.uploadEndpoint: "https://klip.integralmarketing.agency",
            K.mailApiToken: "",
            K.mailFrom: "miguel.ibarra@integralmarketing.agency",
            K.mailMethod: MailMethod.oauth.rawValue,
            K.smtpHost: "",
            K.smtpPort: 587,
            K.smtpUser: "",
            K.smtpFrom: "",
            K.googleClientId: "",
            K.googleClientSecret: "",
            K.googleAccountEmail: ""
        ])
        maxItems = d.integer(forKey: K.maxItems)
        combo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode)),
                         carbonModifiers: UInt32(d.integer(forKey: K.mods)))
        autoPaste = d.object(forKey: K.autoPaste) as? Bool ?? true
        ignoreConcealed = d.object(forKey: K.concealed) as? Bool ?? true
        ignoreTransient = d.object(forKey: K.transient) as? Bool ?? true
        ignoreAutoGenerated = d.object(forKey: K.autoGen) as? Bool ?? true
        excludedBundleIDs = d.stringArray(forKey: K.excluded) ?? []
        captureSource = d.object(forKey: K.captureSrc) as? Bool ?? true
        detectRemoteSource = d.object(forKey: K.detectRem) as? Bool ?? true
        transcriptionModel = d.string(forKey: K.transModel) ?? "gpt-4o-mini-transcribe"
        geminiModel = d.string(forKey: K.geminiModel) ?? "gemini-flash-latest"
        transcriptionLanguage = d.string(forKey: K.transLang) ?? "es"
        aiProvider = d.string(forKey: K.aiProv) ?? "openai"
        transcriptionFallback = d.object(forKey: K.transFallback) as? Bool ?? true
        alwaysOnTop = d.object(forKey: K.alwaysOnTop) as? Bool ?? false
        overrideSystemCapture = d.object(forKey: K.overrideCmd4) as? Bool ?? false
        pendingCmd4Verify = d.object(forKey: K.pendingCmd4Verify) as? Bool ?? false
        voiceCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode2)),
                              carbonModifiers: UInt32(d.integer(forKey: K.mods2)))
        captureCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode3)),
                                carbonModifiers: UInt32(d.integer(forKey: K.mods3)))
        uiLanguage = d.string(forKey: K.uiLang) ?? "en"
        uploadEndpoint = d.string(forKey: K.uploadEndpoint) ?? "https://klip.integralmarketing.agency"
        mailApiToken = d.string(forKey: K.mailApiToken) ?? ""
        mailFrom = d.string(forKey: K.mailFrom) ?? "miguel.ibarra@integralmarketing.agency"
        // Migración: el método DWD se retiró (impersonaba a cualquiera del dominio). Quien lo tuviera
        // guardado pasa a Google Workspace (OAuth per-usuario), que solo envía como uno mismo.
        mailMethod = MailMethod(rawValue: d.string(forKey: K.mailMethod) ?? "oauth") ?? .oauth
        smtpHost = d.string(forKey: K.smtpHost) ?? ""
        smtpPort = d.object(forKey: K.smtpPort) as? Int ?? 587
        smtpUser = d.string(forKey: K.smtpUser) ?? ""
        smtpFrom = d.string(forKey: K.smtpFrom) ?? ""
        googleClientId = d.string(forKey: K.googleClientId) ?? ""
        googleClientSecret = d.string(forKey: K.googleClientSecret) ?? ""
        googleAccountEmail = d.string(forKey: K.googleAccountEmail) ?? ""

        // Migración única: el default de captura pasó de ⌘⇧2 a ⌘⇧U (⌘⇧2 lo secuestraban apps como Loom).
        // A quien siga con el viejo ⌘⇧2 persistido, moverlo a ⌘⇧U. Si el usuario eligió otro atajo, respetarlo.
        let migCaptureKey = "migratedCaptureToU"
        if !d.bool(forKey: migCaptureKey) {
            if captureCombo == KeyCombo.legacyCaptureCombo { captureCombo = KeyCombo.defaultCaptureCombo }
            d.set(true, forKey: migCaptureKey)
        }
    }

    func addExcludedApp(_ id: String) {
        guard !id.isEmpty, !excludedBundleIDs.contains(id) else { return }
        excludedBundleIDs.append(id)
    }

    func removeExcludedApp(_ id: String) {
        excludedBundleIDs.removeAll { $0 == id }
    }

    // MARK: - Migración del dominio antiguo (Pasta → Klip)

    private static let migratedFlagKey = "migratedFromPastaClip"

    private static func migrateLegacyDefaultsIfNeeded() {
        let std = UserDefaults.standard
        guard !std.bool(forKey: migratedFlagKey) else { return }
        defer { std.set(true, forKey: migratedFlagKey) }
        guard let legacy = UserDefaults(suiteName: "com.proper.pastaclip") else { return }
        // No migramos el atajo (queremos el nuevo ⌃⇧V por defecto) ni didAutoEnableLogin
        // (Klip se registra bajo su nueva identidad).
        let keys = [K.maxItems, K.autoPaste, K.concealed, K.transient, K.autoGen, K.excluded]
        for key in keys {
            if let value = legacy.object(forKey: key), std.object(forKey: key) == nil {
                std.set(value, forKey: key)
            }
        }
    }
}
